Update engineer's manual on rm_manual
rm-controls/rm_manual pull request #11
Opened 2022-07-10 11:15 UTC by ljq-lv

2022-07-15 10:23 UTC, qiayuanliao requested changes
按住 shift 不同速度的代码步兵英雄已经有了，你为什么要重复写？

2022-07-21 08:57 UTC, ljq-lv commented on include/rm_manual/engineer_manual.h
> +  void ctrlVPress();  // home sky
这个已经改了 然后低速模式的话 在我写低速模式的时候 步兵英雄是没有相关的低速模式的代码的 他们是shift变成小陀螺模式 所以我自己重复写了一个低速模式

2022-07-21 08:58 UTC, ljq-lv commented on src/engineer_manual.cpp
> +//
大量注释 是当时为了测试 晚点pr的就是完整的 没有注释的版本

2022-07-27 10:12 UTC, ye-luo-xi-tui approved these changes

2022-07-27 10:20 UTC, ye-luo-xi-tui commented
如何进入低速模式？似乎没有看见相关代码

2022-07-27 12:14 UTC, ye-luo-xi-tui commented
> 如何进入低速模式？似乎没有看见相关代码

@ljq-lv

2022-07-27 12:36 UTC, ye-luo-xi-tui approved these changes

2022-07-27 12:36 UTC, ye-luo-xi-tui commented on include/rm_manual/engineer_manual.h
> +#include <std_srvs/Empty.h>
这是啥

2022-07-29 01:42 UTC, Edwinlinks commented on src/engineer_manual.cpp
> +  std::cout << "do " + prefix_ + root_ << std::endl;
应该使用 ROS_INFO 代替 std::cout，下面同理

2022-07-30 02:08 UTC, Edwinlinks approved these changes

2022-10-22 13:10 UTC, caijiefeng approved these changes

2022-10-26 12:16 UTC, qiayuanliao commented
咋关闭了

2022-10-26 13:41 UTC, ljq-lv commented
> 咋关闭了

操作失误 不小心给关掉了（捂脸），重新又开了一个

2022-10-27 03:20 UTC, closed without merging