Complete the manual part of manual separation
rm-controls/rm_manual pull request #13
Opened 2022-07-27 12:23 UTC by chenhuiYu00

rm_referee未包含进主仓库，rm_manual缺少依赖导致ci还未通过。

2022-07-27 12:40 UTC, ye-luo-xi-tui commented on include/rm_manual/common/data.h
> +  rm_msgs::ManualToReferee manual_to_referee_pub_data;
下划线警察出警！

2022-07-27 12:59 UTC, ye-luo-xi-tui requested changes
1

2022-07-28 07:42 UTC, qiayuanliao requested changes
- data 这个类根本就没必要存在
- 所有头文件都不符合code style `#proma once`

2022-07-28 07:42 UTC, qiayuanliao commented on CMakeLists.txt
> +        rm_referee
rm的东西放在一起

2022-07-28 07:42 UTC, qiayuanliao commented on include/rm_manual/common/data.h
> +
rm的东西放在一起

2022-07-28 07:42 UTC, qiayuanliao commented on include/rm_manual/common/data.h
> +
头文件要分类，放在一起，你看着不难受吗？混来混去夹来夹去

2022-07-28 07:42 UTC, qiayuanliao commented on include/rm_manual/common/data.h
> +  rm_msgs::ManualToReferee manual_to_referee_pub_data_;
分类，同类放一起，不要夹...

2022-07-28 07:42 UTC, qiayuanliao commented on package.xml
> +    <depend>rm_referee</depend>
分好类 按类型放在一起

2022-07-28 07:42 UTC, qiayuanliao commented on package.xml
> +    <depend>rm_referee</depend>
看别的包怎么搞的

2022-07-29 12:23 UTC, ye-luo-xi-tui commented on include/rm_manual/common/manual_base.h
> +#include <sensor_msgs/JointState.h>
重复包含头文件

2022-07-29 12:43 UTC, ye-luo-xi-tui commented
@ljq-lv 来帮忙review一下工程相关部分

2022-07-29 12:46 UTC, ye-luo-xi-tui commented on include/rm_manual/common/manual_base.h
> +#include <rm_referee/referee/referee.h>
这个头文件似乎并没有用到

2022-07-29 12:57 UTC, ye-luo-xi-tui commented
@Edwinlinks 凯子哥快来

2022-08-02 08:12 UTC, ye-luo-xi-tui commented
@Edwinlinks @ljq-lv 假期别松懈，速

2022-09-21 15:35 UTC, qiayuanliao approved these changes

2022-09-22 08:56 UTC, ye-luo-xi-tui approved these changes

2022-09-22 08:56 UTC, merged