Update command sender.
rm-controls/rm_manual pull request #27
Opened 2022-12-09 06:57 UTC by chenhuiYu00

对 #22 再次pr

2022-12-11 14:12 UTC, qiayuanliao requested changes
错漏百出

2022-12-11 14:12 UTC, qiayuanliao commented on include/rm_manual/common/manual_base.h
>    sensor_msgs::JointState joint_state_;
似乎是多余的，飞镖的command sender 要改

2022-12-11 14:12 UTC, qiayuanliao commented on include/rm_manual/common/manual_base.h
>    rm_msgs::TrackData track_data_;
似乎是多余的， ShooterCommandSender 要改

2022-12-11 14:12 UTC, qiayuanliao commented on include/rm_manual/common/manual_base.h
这行的上面11行 所有 ros::Subscriber 都写成一行就行了吧

2022-12-11 14:12 UTC, qiayuanliao commented on include/rm_manual/common/manual_base.h
>    rm_msgs::GimbalDesError gimbal_des_error_;
似乎是多余的，若不是多余的，则某个 CommandSender 要改

2022-12-29 16:47 UTC, qiayuanliao approved these changes

2022-12-29 16:47 UTC, qiayuanliao commented on include/rm_manual/chassis_gimbal_manual.h
> +  void mouseMidRise(int m_z);
这里的处理有点诡异，之后可以想想怎么改好

2022-12-29 16:51 UTC, qiayuanliao commented
CI 没过

2023-01-01 02:12 UTC, chenhuiYu00 commented on include/rm_manual/chassis_gimbal_manual.h
> +  void mouseMidRise(int m_z);
之前讨论的结果是传值进去，目前我不知道怎么改..

2023-01-01 07:30 UTC, ye-luo-xi-tui approved these changes

2023-01-01 07:31 UTC, merged