Updated the remote control key of dart.
rm-controls/rm_manual pull request #32
Opened 2023-01-11 13:18 UTC by d0h0s

#将飞镖的左拨杆调整为
    上：拨弹盘上升    中：拨弹盘停止    下：拨弹盘复位
#将飞镖的右拨杆调整为
    上：开启摩擦轮    中：关闭摩擦轮
#新增发射两枚飞镖后拨弹盘自动停止功能。

2023-01-15 05:53 UTC, ye-luo-xi-tui commented
代码规范估计过不了ci。跑一下pre-commit，配一下clion的clang-format

2023-01-16 00:54 UTC, d0h0s commented
> 代码规范估计过不了ci。跑一下pre-commit，配一下clion的clang-format

收到

2023-01-17 03:29 UTC, d0h0s commented
> 代码规范估计过不了ci。跑一下pre-commit，配一下clion的clang-format
这两个都配好并通过了

2023-01-17 03:32 UTC, d0h0s commented
> 代码规范估计过不了ci。跑一下pre-commit，配一下clion的clang-format

这两个都配好并通过了

2023-01-30 11:15 UTC, ljq-lv commented on include/rm_manual/dart_manual.h
> +  //  void leftSwitchUpFall();
用不到的应该可以直接删了的

2023-01-30 11:16 UTC, ljq-lv commented on include/rm_manual/manual_base.h
> +  std::string robot;
这里robot应该不是临时变量吧

2023-01-31 01:57 UTC, L-SY approved these changes

2023-01-31 08:41 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +  std::string robot;
已更改

2023-01-31 08:42 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +  std::string robot;
> 这里robot应该不是临时变量吧

已更改

2023-02-02 07:58 UTC, chenhuiYu00 commented on src/dart_manual.cpp
> +    trigger_sender_->setPoint(0.);
2.2用具有描述意义的变量取代会不会更好，对于读者来说他们并不知道这个2.2代表着两枚飞镖的移动时间

2023-02-02 08:01 UTC, chenhuiYu00 commented on launch/load.launch
> +    <param name="robot_type" value="robot_type"/>
这一行的作用是什么？我有点忘了，如果是指获取机器人类型的话不是在config里面有吗

2023-02-02 08:07 UTC, Aung-xiao approved these changes

2023-02-04 05:29 UTC, chenhuiYu00 commented on src/dart_manual.cpp
> +    trigger_sender_->setPoint(0.);
@d0h0s

2023-02-04 06:05 UTC, d0h0s commented on src/dart_manual.cpp
> +    trigger_sender_->setPoint(0.);
好的 我6号回学校之后改一下

2023-02-04 06:06 UTC, d0h0s commented on launch/load.launch
> +    <param name="robot_type" value="robot_type"/>
> 这一行的作用是什么？我有点忘了，如果是指获取机器人类型的话不是在config里面有吗

把机器人类型放在参数服务器里，以便在cpp文件里调用

2023-02-05 09:05 UTC, 1moule commented on src/dart_manual.cpp
> +void DartManual::leftSwitchUpRise()
这个函数改成leftSwitchUpOn应该合适点

2023-02-05 09:09 UTC, 1moule commented on include/rm_manual/dart_manual.h
> +  int flag_ = 0;
这个用bool类型感觉好一点

2023-02-05 09:40 UTC, 1moule commented on launch/load.launch
> +    <param name="robot_type" value="robot_type"/>
参数我们都是通过配置文件加载的，把参数写到配置文件里就行

2023-02-05 09:41 UTC, 1moule commented on launch/load.launch
>      <rosparam file="$(find rm_manual)/config/$(arg robot_type).yaml" command="load"/>
这个路径可以修改以下捏

2023-02-05 09:47 UTC, d0h0s commented on src/dart_manual.cpp
> +void DartManual::leftSwitchUpRise()
收到！

2023-02-05 09:47 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  int flag_ = 0;
> 这个用bool类型感觉好一点

收到！

2023-02-05 09:47 UTC, d0h0s commented on launch/load.launch
>      <rosparam file="$(find rm_manual)/config/$(arg robot_type).yaml" command="load"/>
> 这个路径可以修改一下捏

好的👌🏻

2023-02-06 09:54 UTC, Edwinlinks commented on launch/load.launch
> +    "/>
这个rm_config有，不要在这里加

2023-02-06 10:02 UTC, Edwinlinks commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
这里你应该参考其他manual的判断

2023-02-06 10:04 UTC, Edwinlinks requested changes
还缺少command sender 需要的回调函数没有写

2023-02-06 10:36 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
> 为啥要在这里加一个robot的判断

我理解的是pc模式是用键盘控制，rc模式指用遥控器控制。因为飞镖不需要通过键盘控制，所以加了个判断。

2023-02-06 10:45 UTC, d0h0s commented on launch/load.launch
> +    "/>
> 这个rm_config有，不要在这里加

嗯 找到了 在rm_config/rm_manual/dart.yaml里

2023-02-06 12:03 UTC, ye-luo-xi-tui commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
我觉得manual_base的这个函数可以弄成纯虚函数，要这样判断的话c++类的重写特性就没意义了。然后dart_manual继承manual_base重写这个函数。另外一边其他机器人的manual继承manual_base时也对应地重写。

2023-02-06 12:17 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
> 我觉得manual_base的这个函数可以弄成纯虚函数，要这样判断的话c++类的重写特性就没意义了。然后dart_manual继承manual_base重写这个函数。另外一边其他机器人的manual继承manual_base时也对应地重写。

我也觉得这样看起来舒服一点，那我全都改一下？

2023-02-06 16:30 UTC, Edwinlinks commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
> > 为啥要在这里加一个robot的判断
> 
> 我理解的是pc模式是用键盘控制，rc模式指用遥控器控制。因为飞镖不需要通过键盘控制，所以加了个判断。

你这里理解错了呀，飞镖上赛季没有键盘控制，所以方式为了方便在updatePc（拨杆往最上拨）那里写的是飞镖架pitch和yaw的复位功能，你这样安排之后复位那没改呀，你要考虑清楚

2023-02-06 16:51 UTC, d0h0s commented
> 还缺少command sender 需要的回调函数

缺了哪个的回调函数？这个代码部署到飞镖上是没问题的

2023-02-06 16:57 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
> > > 为啥要在这里加一个robot的判断
> > 
> > 我理解的是pc模式是用键盘控制，rc模式指用遥控器控制。因为飞镖不需要通过键盘控制，所以加了个判断。
> 
> 你这里理解错了呀，飞镖上赛季没有键盘控制，所以当时为了方便在updatePc（拨杆往最上拨）那里写的是飞镖架pitch和yaw的复位功能，你这样安排之后复位那没改呀，你要考虑清楚

不会呀 manual_base里有个判断 如果state_是RC就不会进入updatePc函数了

2023-02-06 16:59 UTC, Edwinlinks commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
> > > > 为啥要在这里加一个robot的判断
> > > 
> > > 
> > > 我理解的是pc模式是用键盘控制，rc模式指用遥控器控制。因为飞镖不需要通过键盘控制，所以加了个判断。
> > 
> > 
> > 你这里理解错了呀，飞镖上赛季没有键盘控制，所以当时为了方便在updatePc（拨杆往最上拨）那里写的是飞镖架pitch和yaw的复位功能，你这样安排之后复位那没改呀，你要考虑清楚
> 
> 不会呀 manual_base里有个判断 如果state_是RC就不会进入updatePc函数了

他拨杆最上面不就是pc吗

2023-02-06 17:00 UTC, Edwinlinks commented on include/rm_manual/manual_base.h
> +    if (robot_ == "dart")
> > > > 为啥要在这里加一个robot的判断
> > > 
> > > 
> > > 我理解的是pc模式是用键盘控制，rc模式指用遥控器控制。因为飞镖不需要通过键盘控制，所以加了个判断。
> > 
> > 
> > 你这里理解错了呀，飞镖上赛季没有键盘控制，所以当时为了方便在updatePc（拨杆往最上拨）那里写的是飞镖架pitch和yaw的复位功能，你这样安排之后复位那没改呀，你要考虑清楚
> 
> 不会呀 manual_base里有个判断 如果state_是RC就不会进入updatePc函数了

我的意思是将复位放在了pc，你再仔细看看我的留言

2023-02-06 17:02 UTC, Edwinlinks commented
> > 还缺少command sender 需要的回调函数
> 
> 缺了哪个的回调函数？这个代码部署到飞镖上是没问题的

没事了，没注意到manual_base里面的joint_state回调，这个没问题

2023-02-20 11:37 UTC, chenhuiYu00 commented
commit记录里的描述要写清除，”Fixed some details.“太泛泛而谈了

2023-02-20 11:46 UTC, Edwinlinks reviewed
updatePc裏面的內容還沒有按照昨晚的要求改好

2023-02-20 11:47 UTC, Edwinlinks commented on include/rm_manual/dart_manual.h
> +  }
這部分昨晚不是說了不用嗎，還在這加個改變狀態的函數幹啥

2023-02-20 11:47 UTC, d0h0s commented
> updatePc裏面的內容還沒有按照昨晚的要求改好

之后又看了一下，用纯虚函数的接口就能实现了

2023-02-20 11:47 UTC, Edwinlinks commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
這個狀態在哪裏有用到

2023-02-20 11:48 UTC, d0h0s commented
> commit记录里的描述要写清除，”Fixed some details.“太泛泛而谈了

收到

2023-02-20 11:50 UTC, d0h0s commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
原来的状态就是这样写的，我觉得是表示空闲吧

2023-02-20 12:00 UTC, d0h0s commented
> > > updatePc裏面的內容還沒有按照昨晚的要求改好
> > 
> > 之后又看了一下，用纯虚函数的接口就能实现了
> 
> 不是呀，我昨晚就说了这种实现方式并不妥当，所以才叫你改的，不是说你用这种方法实现了就行，你要弄清楚我昨晚让你改的原因呀

好的👌🏻 我今晚就改

2023-02-20 12:04 UTC, Edwinlinks commented
> > > > updatePc裏面的內容還沒有按照昨晚的要求改好
> > > 
> > > 
> > > 之后又看了一下，用纯虚函数的接口就能实现了
> > 
> > 
> > 不是呀，我昨晚就说了这种实现方式并不妥当，所以才叫你改的，不是说你用这种方法实现了就行，你要弄清楚我昨晚让你改的原因呀
> 
> 好的👌🏻 我今晚就改

要是不清楚需求要记得直接问，不然你后面工作也不好展开，做了还会有问题

2023-02-20 12:05 UTC, d0h0s commented
> > > > > updatePc裏面的內容還沒有按照昨晚的要求改好
> > > > 
> > > > 
> > > > 之后又看了一下，用纯虚函数的接口就能实现了
> > > 
> > > 
> > > 不是呀，我昨晚就说了这种实现方式并不妥当，所以才叫你改的，不是说你用这种方法实现了就行，你要弄清楚我昨晚让你改的原因呀
> > 
> > 好的👌🏻 我今晚就改
> 
> 要是不清楚需求要记得直接问，不然你后面工作也不好展开，做了还会有问题

明白了🥺

2023-02-22 01:00 UTC, ljq-lv commented
改好的部分 按一下resloved

2023-02-22 01:21 UTC, d0h0s commented
> 改好的部分 按一下resloved

好的

2023-02-25 12:48 UTC, L-SY approved these changes

2023-02-26 07:04 UTC, Edwinlinks commented on include/rm_manual/manual_base.h
> +
咋还有这个state

2023-02-26 07:06 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +
这个是之前就有的，确实没什么用，那我直接删掉了？

2023-02-26 07:07 UTC, Edwinlinks commented on include/rm_manual/manual_base.h
> +
> 这个是之前就有的，确实没什么用，那我直接删掉了？

没用就删了，不要留没用的代码

2023-02-26 07:11 UTC, d0h0s commented on include/rm_manual/manual_base.h
> +
已改

2023-02-26 07:35 UTC, Edwinlinks commented on src/dart_manual.cpp
> +}
漏了调用父类的dbusDataCallback

2023-03-17 09:03 UTC, d0h0s commented
此pr代码管理不规范，因此先close。开新分支后再pr

2023-03-17 09:04 UTC, d0h0s commented
本pr没有开新分支，直接在master上更改代码了。因此先close，之后再开个新pr。

2023-03-17 09:06 UTC, closed without merging