New function for dart
rm-controls/rm_manual pull request #45
Opened 2023-03-17 10:22 UTC by d0h0s

#将飞镖的左拨杆调整为
上：拨弹盘上升 中：拨弹盘停止 下：拨弹盘复位
#将飞镖的右拨杆调整为
上：开启摩擦轮 中：关闭摩擦轮 下：回到上次记录的pitch、yaw位置
#发射两枚飞镖后拨弹盘自动停止。
#光电门检测发射的是第几枚飞镖，并改变摩擦轮转速。
#左上扭盘功能：
顺时针扭一次：切换基地射速（BASE_MODE），再扭一次切换回普通射速（NORMAL_MODE）
逆时针扭一次，切换成pitch、yaw微调模式

2023-03-18 13:33 UTC, L-SY reviewed
有没有可能左拨杆上是预备（转到摩擦轮之前一点），中是发射（再往前推一点）

2023-03-18 13:44 UTC, d0h0s commented
> 有没有可能左拨杆上是预备（转到摩擦轮之前一点），中是发射（再往前推一点）

没懂你意思

2023-03-21 09:12 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  bool flag_ = 0;
> 这个flag干嘛用的

实现让trigger转固定时间功能时使用的。左拨杆拨到最上时，记录当前时间，flag由0变1，flag不为0就不记录。flag重新置0的代码写在left_mid回调函数中，只有把左拨杆拨回中间再拨到上面才能进行后两发飞镖的发射。

2023-04-03 09:59 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  if (dart_fired_num_ != 2)
如果在发射第三第四枚时退出，之后就会有bug再也发射不了

2023-04-03 10:01 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
>    double qd_, upward_vel_;
这个qd作为局部变量

2023-04-03 10:38 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (dart_fired_num_ != 2)
已改成当已发射飞镖枚数小于2时，进入if

2023-04-03 10:41 UTC, d0h0s commented on include/rm_manual/dart_manual.h
>    double qd_, upward_vel_;
由于要在右拨杆上位的高电平触发中断函数中不断更新摩擦轮转速以保证模式切换后摩擦轮转速切换的及时性，因此这里需要将qd_作为全局变量。

2023-04-10 07:47 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +#include "rm_msgs/GameRobotStatus.h"
其他软件包的头文件使用尖括号

2023-04-10 07:53 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +  //  void leftSwitchDownRise() override;
别出现注释

2023-04-10 07:54 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +  void leftSwitchFree(const rm_msgs::DbusData::ConstPtr& data) override
这是什么意思，免费？自由？

2023-04-10 07:55 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +  rm_msgs::GameRobotStatus::ConstPtr game_robot_status_data_;
把data去掉吧，排查一下还有哪些地方可以删掉额外的data

2023-04-10 08:03 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +}
直接叫`launchTwoDart`会不会更好哈哈哈

2023-04-10 08:04 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +void DartManual::dartFiredNumChanged()
`getDartLaunchedNum`?

2023-04-10 08:14 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  if (outpost_hp_ == 0)
else即可

2023-04-10 08:16 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +    qd_ = qd_base_[dart_fired_num_];
为什么是先设置好转速再判断转速应是多少？

2023-04-10 08:17 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  if (last_dart_door_status_ - dart_client_cmd_data_->dart_launch_opening_status == 2)
我没看裁判系统协议，为啥是这样判断飞镖门开启次数的

2023-04-10 08:20 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
>    }
上面不是判断过前哨站血量并且设置了转速pitch yaw吗？这段是干嘛的

2023-04-10 10:14 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +#include "rm_msgs/GameRobotStatus.h"
好的👌🏻

2023-04-10 10:15 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  //  void leftSwitchDownRise() override;
收到

2023-04-10 10:23 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  void leftSwitchFree(const rm_msgs::DbusData::ConstPtr& data) override
自由的意思，因为本来在manual_base里，左侧拨杆event的update写在了updateRC里，就是会受右侧拨杆状态切换的制约。然而飞镖左拨杆下键位是recordPosition模式的触发方式，触发时摇杆需要不能控制移动，因此state_在leftSwitchDownOn触发时要切换到RC以外的状态（我写的是IDLE）。如果不写LeftSwitchFree（本质是用纯虚函数接口把左摇杆event的update从updateRC中移出至dbus中断函数中），左侧拨杆就无法靠自己切换状态，而左拨杆从左下切到左中后是需要切换到RC模式的。

2023-04-10 10:24 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  rm_msgs::GameRobotStatus::ConstPtr game_robot_status_data_;
这里是设置全局变量把数据从referee相关话题中取出来。

2023-04-10 10:25 UTC, d0h0s commented on src/dart_manual.cpp
> +}
确实

2023-04-10 10:32 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (outpost_hp_ == 0)
确实

2023-04-10 10:34 UTC, d0h0s commented on src/dart_manual.cpp
> +    qd_ = qd_base_[dart_fired_num_];
当时写代码想着一切换auto模式摩擦轮就开始转。不过都是写在高电平触发函数里，孰先孰后没有关系

2023-04-10 10:35 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (last_dart_door_status_ - dart_client_cmd_data_->dart_launch_opening_status == 2)
飞镖门关闭时为1
飞镖门正在开启/关闭为2
飞镖门完全开启为0

2023-04-10 10:36 UTC, d0h0s commented on src/dart_manual.cpp
> +void DartManual::dartFiredNumChanged()
改了改了

2023-04-10 10:40 UTC, d0h0s commented on src/dart_manual.cpp
>    }
当前哨站血量不为0，瞄准前哨站，反之瞄准基地；
飞镖门完全开启时，自动发射飞镖；
当第一次击打前哨站时，射击2枚飞镖即停止；
当瞄准对象为基地时，发射全部飞镖；
摩擦轮转速改变与yaw轴补偿仍生效。

2023-04-10 13:22 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +  rm_msgs::GameRobotStatus::ConstPtr game_robot_status_data_;
> 这里是设置全局变量把数据从referee相关话题中取出来。

我的意思是在命名上去掉名字里的data

2023-04-10 13:24 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +    qd_ = qd_base_[dart_fired_num_];
> 当时写代码想着一切换auto模式摩擦轮就开始转。不过都是写在高电平触发函数里，孰先孰后没有关系

逻辑上很怪异呀，虽然实际效果可能没有区别

2023-04-10 13:27 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +  void leftSwitchFree(const rm_msgs::DbusData::ConstPtr& data) override
> 自由的意思，因为本来在manual_base里，左侧拨杆event的update写在了updateRC里，就是会受右侧拨杆状态切换的制约。然而飞镖左拨杆下键位是recordPosition模式的触发方式，触发时摇杆需要不能控制移动，因此state_在leftSwitchDownOn触发时要切换到RC以外的状态（我写的是IDLE）。如果不写LeftSwitchFree（本质是用纯虚函数接口把左摇杆event的update从updateRC中移出至dbus中断函数中），左侧拨杆就无法靠自己切换状态，而左拨杆从左下切到左中后是需要切换到RC模式的。

直接重载updateRC，在另一个合适的位置更新event就好了呀。

2023-04-10 13:29 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
>    }
> 当前哨站血量不为0，瞄准前哨站，反之瞄准基地； 飞镖门完全开启时，自动发射飞镖； 当第一次击打前哨站时，射击2枚飞镖即停止； 当瞄准对象为基地时，发射全部飞镖； 摩擦轮转速改变与yaw轴补偿仍生效。

但是前面已经所有东西都设置好了呀，还是说前面所有的东西都是手动的最后才来个自动来覆盖？

2023-04-10 13:35 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
>    }
> > 当前哨站血量不为0，瞄准前哨站，反之瞄准基地； 飞镖门完全开启时，自动发射飞镖； 当第一次击打前哨站时，射击2枚飞镖即停止； 当瞄准对象为基地时，发射全部飞镖； 摩擦轮转速改变与yaw轴补偿仍生效。
> 
> 但是前面已经所有东西都设置好了呀，还是说前面所有的东西都是手动的最后才来个自动来覆盖？

又看了一下，似乎前面是设置好pitch yaw 转速，最后是设置拨盘速度，好像又没问题

2023-04-10 13:35 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  void leftSwitchFree(const rm_msgs::DbusData::ConstPtr& data) override
> > 自由的意思，因为本来在manual_base里，左侧拨杆event的update写在了updateRC里，就是会受右侧拨杆状态切换的制约。然而飞镖左拨杆下键位是recordPosition模式的触发方式，触发时摇杆需要不能控制移动，因此state_在leftSwitchDownOn触发时要切换到RC以外的状态（我写的是IDLE）。如果不写LeftSwitchFree（本质是用纯虚函数接口把左摇杆event的update从updateRC中移出至dbus中断函数中），左侧拨杆就无法靠自己切换状态，而左拨杆从左下切到左中后是需要切换到RC模式的。
> 
> 直接重载updateRC，在另一个合适的位置更新event就好了呀。

直接在重载后的updateRC中更新event并把这个updateRC写在dbus回调函数中吗？

2023-04-10 13:36 UTC, d0h0s commented on src/dart_manual.cpp
> +    qd_ = qd_base_[dart_fired_num_];
已改

2023-04-10 13:42 UTC, ye-luo-xi-tui commented on include/rm_manual/dart_manual.h
> +  void leftSwitchFree(const rm_msgs::DbusData::ConstPtr& data) override
> > > 自由的意思，因为本来在manual_base里，左侧拨杆event的update写在了updateRC里，就是会受右侧拨杆状态切换的制约。然而飞镖左拨杆下键位是recordPosition模式的触发方式，触发时摇杆需要不能控制移动，因此state_在leftSwitchDownOn触发时要切换到RC以外的状态（我写的是IDLE）。如果不写LeftSwitchFree（本质是用纯虚函数接口把左摇杆event的update从updateRC中移出至dbus中断函数中），左侧拨杆就无法靠自己切换状态，而左拨杆从左下切到左中后是需要切换到RC模式的。
> > 
> > 
> > 直接重载updateRC，在另一个合适的位置更新event就好了呀。
> 
> 直接在重载后的updateRC中更新event并把这个updateRC写在重载的dbus回调函数中吗？

另一个合适的地方更新event就好了

2023-04-10 15:21 UTC, qiayuanliao commented
在强调一次，请 resolve 所有 conversation 再找我 review！！！
弄完再 艾特 我

2023-04-10 15:24 UTC, d0h0s commented
> 在强调一次，请 resolve 所有 conversation 再找我 review！！！ 弄完再 艾特 我
好的，我记得了

2023-04-10 15:43 UTC, qiayuanliao commented
> > 在强调一次，请 resolve 所有 conversation 再找我 review！！！ 弄完再 艾特 我
> > 好的，我记得了

教他正确使用 markdown @ye-luo-xi-tui @BruceLannn

2023-04-13 12:51 UTC, chenhuiYu00 commented on src/dart_manual.cpp
> +  if (last_dart_door_status_ - dart_client_cmd_data_->dart_launch_opening_status == 2)
把这个加在DartClientCmd.msg吧，当时写msg的忘写了。写个2看代码的时候很难懂

2023-04-13 16:00 UTC, d0h0s commented on src/dart_manual.cpp
> +  launch_position_4_ = getParam(nh_trigger, "launch_position_4", 0.);
行 我改下

2023-04-13 16:04 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (last_dart_door_status_ - dart_client_cmd_data_->dart_launch_opening_status == 2)
> 把这个加在DartClientCmd.msg吧，当时写msg的忘写了。写个2看代码的时候很难懂

好的嘞

2023-04-14 08:33 UTC, NaHCO3bc commented on include/rm_manual/engineer_manual.h
> +  }
这些飞镖的函数为啥要写进engineer的manual里

2023-04-14 08:40 UTC, NaHCO3bc commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
这些新加的函数是干啥用的，state的赋值为什么不写在原有的rightSwitchDownRise里

2023-04-14 08:53 UTC, NaHCO3bc commented on include/rm_manual/dart_manual.h
> +  }
同上

2023-04-14 09:29 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +}
> 这个1 -1什么的用msg的枚举，这样写怎么知道是啥意思

它是一个在-1和1之间变化的浮点数。。。哪来的枚举

2023-04-14 09:48 UTC, d0h0s commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
> 这些新加的函数是干啥用的，state的赋值为什么不直接写进rightSwitchDownRise()里，为啥写个xxxstate()

在manual_base.h中定义xxxstate()为纯虚函数接口，不同的机器人通过在xxxstate()中改变state_实现状态切换。例如rightSwitchDownOnState()，因为右拨杆下位的功能是自动托管模式（后面也可能改为PC模式），期间飞镖不会被摇杆控制，设置state_为PC，而这与步兵右拨杆下位设定的状态（state_=IDLE）是冲突的。为了在解决上述问题的同时保证代码规范，这里使用纯虚函数接口的形式实现。
至于leftSwitchFree，在上面的评论中有提到。

2023-04-14 09:49 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  }
> 同上

同上

2023-04-14 09:50 UTC, d0h0s commented on include/rm_manual/engineer_manual.h
> +  }
> 为什么把飞镖用的东西写进工程的manual里

因为在manual_base.h中设置了纯虚函数接口。

2023-04-14 10:40 UTC, NaHCO3bc commented on src/dart_manual.cpp
> +}
> > 这个1 -1什么的用msg的枚举，这样写怎么知道是啥意思
> 
> 它是一个在-1和1之间变化的浮点数。。。哪来的枚举

没事了看错了

2023-04-14 11:07 UTC, NaHCO3bc commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
> 

你这不如把manual_base里的赋值去掉，在chassis_gimbal_manual里把重写原来manual_base的赋值，你在dart_manual写你需要的state赋值就可以了，而不是加了这些奇奇怪怪的xxxstate()

2023-04-14 11:08 UTC, NaHCO3bc commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
> > 这些新加的函数是干啥用的，state的赋值为什么不直接写进rightSwitchDownRise()里，为啥写个xxxstate()
> 
> 在manual_base.h中定义xxxstate()为纯虚函数接口，不同的机器人通过在xxxstate()中改变state_实现状态切换。例如rightSwitchDownOnState()，因为右拨杆下位的功能是自动托管模式（后面也可能改为PC模式），期间飞镖不会被摇杆控制，设置state_为PC，而这与步兵右拨杆下位设定的状态（state_=IDLE）是冲突的。为了在解决上述问题的同时保证代码规范，这里使用纯虚函数接口的形式实现。 至于leftSwitchFree，在上面的评论中有提到。

你这不如把manual_base里的赋值去掉，在chassis_gimbal_manual里把重写原来manual_base的赋值，你在dart_manual写你需要的state赋值就可以了，而不是加了这些奇奇怪怪的xxxstate()

2023-04-14 11:39 UTC, d0h0s commented on include/rm_manual/chassis_gimbal_manual.h
> +  }
我之前是像你说的这样写，振羽哥说改成用纯虚函数接口

2023-04-15 05:20 UTC, L-SY commented
> > 有没有可能左拨杆上是预备（转到摩擦轮之前一点），中是发射（再往前推一点）
> 
> 没懂你意思

当时觉得用位置控制同步带可能会好点，但是似乎差别不大

2023-04-15 05:23 UTC, L-SY commented
> > 有没有可能左拨杆上是预备（转到摩擦轮之前一点），中是发射（再往前推一点）
> 
> 没懂你意思

当时觉得位置控制会更加利于控制，因为云台手按下就发射，但是飞镖所有控制都在遥控器上感觉现在这样更好。

2023-04-26 14:54 UTC, ye-luo-xi-tui commented on include/rm_manual/manual_base.h
>    }
一定需要定义一个纯虚函数吗？没必要吧

2023-04-26 14:56 UTC, ye-luo-xi-tui commented on include/rm_manual/engineer_manual.h
> +  }
除飞镖外其他车应该都是IDLE，可能放在chassis_gimbal_manual就行了，并且就给一个变量赋值没必要搞纯虚函数吧，可以直接重写相关 函数的。

2023-04-27 04:58 UTC, d0h0s commented on include/rm_manual/engineer_manual.h
> +  }
> 除飞镖外其他车应该都是IDLE，可能放在chassis_gimbal_manual就行了，并且就给一个变量赋值没必要搞纯虚函数吧，可以直接重写相关 函数的。

那state_的改变就和拨杆功能写在一起了？都放在子类的cpp文件里

2023-04-27 06:49 UTC, d0h0s commented on include/rm_manual/engineer_manual.h
> +  }
已改

2023-04-29 08:10 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
这个`launch_rest_flag_`似乎是个局部变量就可以了？只需要进入该函数时判断一次已发射飞镖数量

2023-04-29 08:12 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  launch_position_4_ = getParam(nh_trigger, "launch_position_4", 0.014457);
为什么发射位置是从2开始计数

2023-04-29 09:45 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
leftSwitchMidRise、rightSwitchDownOn里也改变了这个变量

2023-04-29 09:46 UTC, d0h0s commented on src/dart_manual.cpp
> +  launch_position_4_ = getParam(nh_trigger, "launch_position_4", 0.014457);
改成“已发射一枚飞镖后trigger停留的位置”了

2023-04-29 14:28 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
> leftSwitchMidRise、rightSwitchDownOn里也改变了这个变量

这个逻辑似乎有些没搞清楚，`launch_rest_flag_`的赋值是根据什么决定的？跟什么功能相关

2023-04-29 14:36 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
这是个flag标志位，0表示不要射出剩余的飞镖，1表示射出剩余的飞镖

2023-04-29 14:48 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
> 这是个flag标志位，0表示不要射出剩余的飞镖，1表示射出剩余的飞镖

`leftSwitchMidRise`为什么要把它赋为1呢？似乎没有找到对应的功能描述。`rightSwitchDownOn`里会先判断是第几次射前哨站来给它赋值，但最核心的判断条件也是已发射飞镖数（第几次开门没太大意义）。和`launchTwoDart`里难道不是重合的吗

2023-04-29 14:49 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +      if (outpost_hp_ != 0 && dart_fired_num_ <= 2)
应该是小于2？

2023-04-29 14:54 UTC, ye-luo-xi-tui commented on src/dart_manual.cpp
> +  launch_position_4_ = getParam(nh_trigger, "launch_position_4", 0.014457);
> 改成“已发射一枚飞镖后trigger停留的位置”了

没懂，似乎没有任何修改

2023-05-09 07:02 UTC, d0h0s commented on src/dart_manual.cpp
> +      if (outpost_hp_ != 0 && dart_fired_num_ <= 2)
> 应该是小于2？

一定得是等于2，launchTwoDart()里dart_fired_num_ == 2 && launch_rest_flag_ == 0才能使trigger停止

2023-05-09 07:23 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
> > 这是个flag标志位，0表示不要射出剩余的飞镖，1表示射出剩余的飞镖
> 
> `leftSwitchMidRise`为什么要把它赋为1呢？似乎没有找到对应的功能描述。`rightSwitchDownOn`里会先判断是第几次射前哨站来给它赋值，但最核心的判断条件也是已发射飞镖数（第几次开门没太大意义）。和`launchTwoDart`里难道不是重合的吗

发射剩下两枚飞镖需要把左拨杆拨到中间再拨到上面。launch_rest_flag_初始值为1，左拨杆拨上后，若此时dart_fired_num_小于2则launch_rest_flag_会在if (dart_fired_num_ < 2)中被置0，等dart_fired_num_==2时trigger停止。将左拨杆拨到中间再拨到上面，此时launch_rest_flag_值为1，因进入不了if (dart_fired_num_ < 2)而保持launch_rest_flag_=1，进入if (dart_fired_num_ >= 2 && launch_rest_flag_ == 1)使trigger上升。注意，launchTwoDart需要在高电平触发函数中被使用。dart_fired_num_==2是一个节点，既是发射前两枚的末尾状态，又是发射后两枚的初始状态。从这个角度看，为了区分这两种状态，dart_fired_num_的存在也是必须的。

2023-05-09 07:23 UTC, d0h0s commented on src/dart_manual.cpp
> +  if (dart_fired_num_ == 2 && launch_rest_flag_ == 0)
> > 这是个flag标志位，0表示不要射出剩余的飞镖，1表示射出剩余的飞镖
> 
> `leftSwitchMidRise`为什么要把它赋为1呢？似乎没有找到对应的功能描述。`rightSwitchDownOn`里会先判断是第几次射前哨站来给它赋值，但最核心的判断条件也是已发射飞镖数（第几次开门没太大意义）。和`launchTwoDart`里难道不是重合的吗

发射剩下两枚飞镖需要把左拨杆拨到中间再拨到上面。launch_rest_flag_初始值为1，左拨杆拨上后，若此时dart_fired_num_小于2则launch_rest_flag_会在if (dart_fired_num_ < 2)中被置0，等dart_fired_num_==2时trigger停止。将左拨杆拨到中间再拨到上面，此时launch_rest_flag_值为1，因进入不了if (dart_fired_num_ < 2)而保持launch_rest_flag_=1，进入if (dart_fired_num_ >= 2 && launch_rest_flag_ == 1)使trigger上升。注意，launchTwoDart需要在高电平触发函数中被使用。dart_fired_num_==2是一个节点，既是发射前两枚的末尾状态，又是发射后两枚的初始状态。从这个角度看，为了区分这两种状态，launch_rest_flag_的存在也是必须的。

2023-05-11 16:14 UTC, ye-luo-xi-tui commented
@qiayuanliao

2023-05-12 16:57 UTC, qiayuanliao requested changes
暂时先看到这。

你的ROS_INFO 的格式和其他人不一样，大家一般都是当句子，首字母大写。

2023-05-12 16:57 UTC, qiayuanliao commented on include/rm_manual/dart_manual.h
> +  }
这种复杂的类的函数定义都应该写在.cpp吧？就这两个单独的函数放这肯定不行啊

2023-05-12 16:57 UTC, qiayuanliao commented on src/dart_manual.cpp
> +  yaw_position_base_ = getParam(nh_yaw, "position_base", 0.);
变量名应统一

2023-05-12 16:57 UTC, qiayuanliao commented on src/dart_manual.cpp
>    gimbal_power_on_event_.update(data->mains_power_gimbal_output);
还需要吗？

2023-05-12 16:57 UTC, qiayuanliao commented on src/manual_base.cpp
> +      updateIDLE(data);
IDLE 是托管模式？

如果是托管其实应该叫 AUTO 模式才对吧？

之前步兵的IDLE的意思是“”开着控制器（云台一直在保持工作，底盘轮子也给着力），但是不对任何遥控器指令做任何反应“”。我不确定现在还是否有这种代码。

2023-05-12 16:57 UTC, qiayuanliao commented on include/rm_manual/dart_manual.h
> +  bool wheel_micro_flag_ = 0, speed_base_flag_ = 0, wheel_speed_flag_ = 0;
根本不应该有这么多flag。

你有三个 Mode 模式：RC、PC、AUTO（IDLE）

两个 Target 目标：OUTPOST、BASE

就已经能覆盖所有情况。

然后在 callback 去修改模式，比如：
- 机器人血量 callback 中判断前哨站血量，若为0则将 target 改为 BASE，根本不需要存 `outpost_hp_` ;
- dbus 数据 callback 中拨杆打到某个地方，则mode改为某个模式;

而不是把这些 callback 数据记录下来然后再弄一堆flag，实在太乱了。

2023-05-12 16:57 UTC, qiayuanliao commented on include/rm_manual/dart_manual.h
> +  rm_msgs::DartClientCmd dart_client_cmd_;
几乎都是没有必要存在的数据

2023-05-12 16:57 UTC, qiayuanliao commented on include/rm_manual/dart_manual.h
>    bool if_stop_{ true };
详细解释一下，这是干啥的，我懒得分析了

2023-05-12 16:58 UTC, qiayuanliao commented
@ye-luo-xi-tui review 质量极低， 罗廷凯为什么没有参与？（帮我艾特他）

2023-05-12 17:34 UTC, ye-luo-xi-tui commented
@Edwinlinks

2023-05-15 06:35 UTC, d0h0s commented on src/dart_manual.cpp
> +  yaw_position_base_ = getParam(nh_yaw, "position_base", 0.);
收到

2023-05-15 06:36 UTC, d0h0s commented on src/dart_manual.cpp
>    gimbal_power_on_event_.update(data->mains_power_gimbal_output);
已经删了

2023-05-15 06:38 UTC, d0h0s commented on src/manual_base.cpp
> +      updateIDLE(data);
> IDLE 是托管模式？
> 
> 如果是托管其实应该叫 AUTO 模式才对吧？
> 
> 之前步兵的IDLE的意思是“”开着控制器（云台一直在保持工作，底盘轮子也给着力），但是不对任何遥控器指令做任何反应“”。我不确定现在还是否有这种代码。

由于自动托管时，要让飞镖遥控器的其他键位都失效，所以在这里用了IDLE模式。确实新增一个AUTO模式比较好。

2023-05-15 06:40 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  bool wheel_micro_flag_ = 0, speed_base_flag_ = 0, wheel_speed_flag_ = 0;
> 根本不应该有这么多flag。
> 
> 你有三个 Mode 模式：RC、PC、AUTO（IDLE）
> 
> 两个 Target 目标：OUTPOST、BASE
> 
> 就已经能覆盖所有情况。
> 
> 然后在 callback 去修改模式，比如：
> 
> * 机器人血量 callback 中判断前哨站血量，若为0则将 target 改为 BASE，根本不需要存 `outpost_hp_` ;
> * dbus 数据 callback 中拨杆打到某个地方，则mode改为某个模式;
> 
> 而不是把这些 callback 数据记录下来然后再弄一堆flag，实在太乱了。

这里的flag是用于翻转的。因为遥控器左上角拨盘的功能是
- 顺时针扭一次：切换基地射速（BASE_MODE），云台回到基地位置；再扭一次切换回普通射速（OUTPOST_MODE），云台回到前哨站位置
- 逆时针扭一次：切换成pitch、yaw微调模式（MICRO_MOVE_MODE），再扭一次回到正常模式(NORMAL_MOVE_MODE)

2023-05-15 06:47 UTC, d0h0s commented
> 暂时先看到这。
> 
> 你的ROS_INFO 的格式和其他人不一样，大家一般都是当句子，首字母大写。

收到，已改。

2023-05-15 07:03 UTC, d0h0s commented
> 暂时先看到这。
> 
> 你的ROS_INFO 的格式和其他人不一样，大家一般都是当句子，首字母大写。

收到，已改。

2023-05-15 07:32 UTC, d0h0s commented on include/rm_manual/dart_manual.h
> +  }
> 这种复杂的类的函数定义都应该写在.cpp吧？就这两个单独的函数放这肯定不行啊

因为改变state_和更新回调函数本来是写在manual_base.cpp和manual_base.h里的，所以感觉全写在dart_manual.cpp的话有点怪。

2023-05-19 11:07 UTC, Edwinlinks commented on src/dart_manual.cpp
> +    yaw_offset_.push_back(yaw_offset[i]);
assert一下是double直接拿来用就行,可以不用这一步，还有就是参数的数量可以适当减少，参考rm_sentry的fsm

2023-05-19 18:06 UTC, Edwinlinks commented on src/dart_manual.cpp
> +    if (outpost_hp_ != 0)
> 最好是在回调里面判断，然后改变状态，然后你这里根据状态来决定是前哨站还是基地位置

其他的flag应该也可以这样子改吧

2023-05-19 18:08 UTC, Edwinlinks commented on src/manual_base.cpp
> +    else if (state_ == IDLE)
这里重载这个回调比较合适吧，而不应该改这里

2023-05-23 06:32 UTC, d0h0s commented on src/dart_manual.cpp
> +    if (outpost_hp_ != 0)
收到，已改

2023-05-23 06:44 UTC, d0h0s commented on src/manual_base.cpp
> +    else if (state_ == IDLE)
收到，已改

2023-05-25 16:19 UTC, qiayuanliao commented
@d0h0s 你这个pr为什么还没改好？都好几天了。

2023-05-25 17:06 UTC, d0h0s commented
> @d0h0s 你这个pr为什么还没改好？都好几天了。

上述提到的问题，除了要修改参数的获取方式以外，其他的都改好了。
因为rm_sentry的fsm是private，我不能直接看到，所以我今天再找庭凯哥要一下链接，看看rm_sentry的fsm是怎么做的。

2023-05-26 04:30 UTC, ye-luo-xi-tui commented
此pr ddl ： 2023.5.26

2023-05-26 17:28 UTC, qiayuanliao approved these changes
不错，不错，做得好。

2023-05-26 17:40 UTC, qiayuanliao commented
CI没过勒

2023-05-26 17:59 UTC, closed without merging