New Speed Mode.
rm-controls/rm_manual pull request #69
Opened 2023-06-26 08:09 UTC by L-SY

### Pr目的：一步步Pr工程的大manual。
#### Pr改动：
- 把原来的两档变速变为四档变速。

2023-06-26 08:10 UTC, L-SY commented
@ye-luo-xi-tui 这个是很久前的改动，分区赛的时候你看过，应该是没问题可以过的。

2023-06-26 12:10 UTC, ye-luo-xi-tui approved these changes

2023-06-26 12:10 UTC, ye-luo-xi-tui commented
合并ddl 6.27

2023-06-27 13:36 UTC, qiayuanliao requested changes
不应该在通用的 ChassisGimbalManual 塞入工程的内容（LOW, EXCHANGE）。显然是不合理的。你可以再派生一个类。

2023-06-27 14:44 UTC, L-SY commented
@ye-luo-xi-tui @qiayuanliao 改了一版，目前只改动了工程的manual。

2023-06-27 14:47 UTC, qiayuanliao reviewed
通过什么函数改变速度模式？我咋没看到。

2023-06-28 10:35 UTC, L-SY commented
> 每次循环都check一次speedmode几乎没有意义。而且不需要 speed_change_scale_，只需要有 speed_scale_ 即可。 何不写一个这样的函数，从而不需要保存 SpeedMode为类成员变量 speed_mode_？
> 
> ```
> void EngineerManual:changeSpeedMode(SpeedMode speed_mode)
> {
>   if (speed_mode == LOW)
>   {
>     speed_scale_ = low_speed_scale_;
>     gyro_speed_ = gyro_low_scale_;
>   }
>   else if (speed_mode == NORMAL)
>   {
>     speed_scale_ = normal_speed_scale_;
>     gyro_speed_ = gyro_normal_scale_;
>   }
>   else if (speed_mode == FAST)
>   {
>     speed_scale_ = fast_speed_scale_;
>     gyro_speed_ = gyro_fast_scale_;
>   }
>   else if (speed_mode == EXCHANGE)
>   {
>     speed_scale_ = exchange_speed_scale_;
>     gyro_speed_ = gyro_exchange_scale_;
>   }
> }
> ```
> 
> @ye-luo-xi-tui 另外，平移和旋转应该统一才对，而不是现在这样“平移是 scale，旋转是直接指定转速 speed”

那我把chassis_gimbal_base里面的东西改一下。
平移和旋转的scale分开的原因是：最开始两个共用一个scale的时候并不一定好开，目前是在不同模式下逐个调。这样虽然看起来不怎么好，但是实际用起来对操作手会友好点。

2023-06-28 10:48 UTC, L-SY commented
##### 目前的manual速度逻辑是：
- 所有兵种可以在对应的manual中通过改变speed_scale来实现移动速度的变化
- 工程目前是通过枚举一个自己专用的四档速度模式，然后在做对应需要速度变化的动作的时候去切换速度类型，然后checkSpeedMode()则是一直运行，来检测目前速度模式，并对应调整。

2023-06-28 16:34 UTC, qiayuanliao requested changes

2023-06-28 16:34 UTC, qiayuanliao commented on src/engineer_manual.cpp
> +    gyro_speed_ = exchange_gyro_scale_;
gyro_speed_ = xxx_scale_?
到底是speed还是scale

2023-06-28 16:35 UTC, qiayuanliao commented
> 

你直接把我说的大部分内容无视掉了，只对我艾特振羽说的事情进行回复...

2023-06-28 16:36 UTC, qiayuanliao commented
> 每次循环都check一次speedmode几乎没有意义。而且不需要 speed_change_scale_，只需要有 speed_scale_ 即可。 何不写一个这样的函数，从而不需要保存 SpeedMode为类成员变量 speed_mode_？
> 
> ```
> void EngineerManual:changeSpeedMode(SpeedMode speed_mode)
> {
>   if (speed_mode == LOW)
>   {
>     speed_scale_ = low_speed_scale_;
>     gyro_speed_ = gyro_low_scale_;
>   }
>   else if (speed_mode == NORMAL)
>   {
>     speed_scale_ = normal_speed_scale_;
>     gyro_speed_ = gyro_normal_scale_;
>   }
>   else if (speed_mode == FAST)
>   {
>     speed_scale_ = fast_speed_scale_;
>     gyro_speed_ = gyro_fast_scale_;
>   }
>   else if (speed_mode == EXCHANGE)
>   {
>     speed_scale_ = exchange_speed_scale_;
>     gyro_speed_ = gyro_exchange_scale_;
>   }
> }
> ```
> 
> @ye-luo-xi-tui 另外，平移和旋转应该统一才对，而不是现在这样“平移是 scale，旋转是直接指定转速 speed”


你直接把我说的大部分内容无视掉了，只对我艾特振羽说的事情进行回复...

2023-06-29 02:37 UTC, L-SY commented on src/engineer_manual.cpp
> +    gyro_speed_ = exchange_gyro_scale_;
已改为speed，之前和平移的混淆了。

2023-06-29 02:41 UTC, L-SY commented on include/rm_manual/engineer_manual.h
> +  SpeedMode speed_mode_;
已把checkSpeedMode()改为setSpeedMode(),删去了speed_mode_类成员。

2023-06-29 02:44 UTC, L-SY commented
> > 每次循环都check一次speedmode几乎没有意义。而且不需要 speed_change_scale_，只需要有 speed_scale_ 即可。 何不写一个这样的函数，从而不需要保存 SpeedMode为类成员变量 speed_mode_？
> > ```
> > void EngineerManual:changeSpeedMode(SpeedMode speed_mode)
> > {
> >   if (speed_mode == LOW)
> >   {
> >     speed_scale_ = low_speed_scale_;
> >     gyro_speed_ = gyro_low_scale_;
> >   }
> >   else if (speed_mode == NORMAL)
> >   {
> >     speed_scale_ = normal_speed_scale_;
> >     gyro_speed_ = gyro_normal_scale_;
> >   }
> >   else if (speed_mode == FAST)
> >   {
> >     speed_scale_ = fast_speed_scale_;
> >     gyro_speed_ = gyro_fast_scale_;
> >   }
> >   else if (speed_mode == EXCHANGE)
> >   {
> >     speed_scale_ = exchange_speed_scale_;
> >     gyro_speed_ = gyro_exchange_scale_;
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @ye-luo-xi-tui 另外，平移和旋转应该统一才对，而不是现在这样“平移是 scale，旋转是直接指定转速 speed”
> 
> 你直接把我说的大部分内容无视掉了，只对我艾特振羽说的事情进行回复...

一开始没想明白这个函数是指什么，是目前这种setSpeedMode这种吗？

2023-07-01 14:21 UTC, ye-luo-xi-tui commented
@qiayuanliao 看看还有什么问题？另外步兵现在也有改变速度模式的需求，到时要在步兵类再一次定义修改速度模式的函数和相关变量吗？

2023-07-02 16:44 UTC, qiayuanliao commented
> > > 每次循环都check一次speedmode几乎没有意义。而且不需要 speed_change_scale_，只需要有 speed_scale_ 即可。 何不写一个这样的函数，从而不需要保存 SpeedMode为类成员变量 speed_mode_？
> > > ```
> > > void EngineerManual:changeSpeedMode(SpeedMode speed_mode)
> > > {
> > >   if (speed_mode == LOW)
> > >   {
> > >     speed_scale_ = low_speed_scale_;
> > >     gyro_speed_ = gyro_low_scale_;
> > >   }
> > >   else if (speed_mode == NORMAL)
> > >   {
> > >     speed_scale_ = normal_speed_scale_;
> > >     gyro_speed_ = gyro_normal_scale_;
> > >   }
> > >   else if (speed_mode == FAST)
> > >   {
> > >     speed_scale_ = fast_speed_scale_;
> > >     gyro_speed_ = gyro_fast_scale_;
> > >   }
> > >   else if (speed_mode == EXCHANGE)
> > >   {
> > >     speed_scale_ = exchange_speed_scale_;
> > >     gyro_speed_ = gyro_exchange_scale_;
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @ye-luo-xi-tui 另外，平移和旋转应该统一才对，而不是现在这样“平移是 scale，旋转是直接指定转速 speed”
> > 
> > 
> > 你直接把我说的大部分内容无视掉了，只对我艾特振羽说的事情进行回复...
> 
> 一开始没想明白这个函数是指什么，是目前这种setSpeedMode这种吗？

没想明白就直接无视是嘛...

2023-07-02 16:45 UTC, qiayuanliao approved these changes

2023-07-02 16:45 UTC, qiayuanliao commented on src/engineer_manual.cpp
> +void EngineerManual::setSpeedMode(std::string speed_mode)
用枚举！！！我函数已经给你写好了！

2023-07-02 16:46 UTC, qiayuanliao requested changes
我再说一次....我函数已经给你写好了！答案给你抄了你是怎么做到连续两次都改出问题的？

2023-07-02 16:47 UTC, qiayuanliao commented on src/engineer_manual.cpp
> +void EngineerManual::setSpeedMode(std::string speed_mode)
没有approve，我按错了

2023-07-02 17:01 UTC, qiayuanliao requested changes

2023-07-02 17:01 UTC, qiayuanliao commented on src/engineer_manual.cpp
> +    gyro_speed_ = exchange_gyro_speed_;
到底是 scale 还是 speed？ 你回复我之后不改？？？

2023-07-02 19:10 UTC, ye-luo-xi-tui commented on include/rm_manual/engineer_manual.h
> +  double angular_z_scale_{}, gyro_scale_{}, fast_gyro_scale_{}, low_gyro_scale_{}, normal_gyro_scale_{},
`angular_z_scale_`似乎是没用到的

2023-07-05 07:30 UTC, qiayuanliao approved these changes

2023-07-06 11:34 UTC, L-SY commented on include/rm_manual/engineer_manual.h
> +  double angular_z_scale_{}, gyro_scale_{}, fast_gyro_scale_{}, low_gyro_scale_{}, normal_gyro_scale_{},
这是之前的manual的问题，在下一次一起改。

2023-07-06 11:38 UTC, merged

2023-07-08 02:54 UTC, ljq-lv commented on include/rm_manual/chassis_gimbal_manual.h
>    double gyro_move_reduction_{ 1. };
同类型的变量应该要合并一起（查了下规范），而且布尔变量用true false初始化 而不是 0 1