Add low_speed mode in standard when opening the cover
rm-controls/rm_manual pull request #76
Opened 2023-07-14 07:50 UTC by liyixin135

2023-07-14 08:49 UTC, ye-luo-xi-tui approved these changes

2023-07-15 02:58 UTC, qiayuanliao requested changes

2023-07-15 02:58 UTC, qiayuanliao commented on src/chassis_gimbal_shooter_cover_manual.cpp
> +  (supply_) ? changeSpeedMode(LOW) : changeSpeedMode(NORMAL);
这个太怪了吧，直接用 if 啊...

2023-07-15 14:00 UTC, qiayuanliao approved these changes

2023-07-16 03:43 UTC, merged